"""LangGraph state definition for Ojas.

The state flows through every node in the graph and accumulates context,
generated code, dependencies, and execution output.
"""

from __future__ import annotations

import operator
from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage


class OjasState(TypedDict):
    """The canonical agent state carried through the LangGraph."""

    # Conversational message history (append-only via operator.add).
    messages: Annotated[list[BaseMessage], operator.add]

    # RAG: relevant code snippets injected by ChromaDB retrieval.
    workspace_context: str

    # The Python script most recently generated by the Coder node.
    generated_code: str

    # Third-party pip dependencies extracted by the Dependency Analyzer.
    dependencies: list[str]

    # stdout + stderr captured from the Docker sandbox execution.
    docker_output: str

    # Number of self-correction attempts in the current cycle.
    retry_count: int

    # Whether the current cycle has completed successfully.
    cycle_complete: bool
